development:
  adapter: postgresql
  encoding: unicode
  database: yelpMap_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: yelpMap_test
  pool: 5
  host: localhost
  min_messages: fatal

production:
  adapter: postgresql
  encoding: unicode
  database: yelpMap_production
  pool: 5
  password:

cucumber:
  <<: *test
